### ISSUE TITLE
Up-Level a Player

### ISSUE THREAD

**Issue by Bauepete** [jfuerlinger/serta#1]
## Story
As a virologist I want to raise a player from one level to the next in order to bring them closer to their final goal.

## Example
Player @jfuerlinger is on level M. 
```
+serta-uplevel @jfuerlinger 
```
Expected response 
```
Level of @jfuerlinger changed from M to C
```

## DoD
- Current level is changed when getting statistics of player
- Bot response with `Not allowed to change level` if this command is issued by a non-virologist
- Bot responses with `No further level to raise` if player is already in the last level

**Comment by jfuerlinger** [comment]
@Bauepete can you please list all the available levels

**Comment by Bauepete** [comment]
- S: Loops
- A: Arrays
- M: Methods
- C: Classes
- F: Files
- P: Greenfoot Serta fighter

**Comment by jfuerlinger** [comment]
Hi @Bauepete,

I've developed the needed logic in the command `serta-uplevel`.

**Sample**
```
!serta-uplevel @jfuerlinger @p.bauer
```

As you can see you can mention more than one person.

There exists also an opposite command => `serta-downlevel`

Please give me feedback.

**Comment by Bauepete** [comment]
All tests passed.
